export * from "./dev.svg";
export * from "./github.svg";
export * from "./linked-in.svg";
export * from "./medium.svg";
export * from "./mastodon.svg";
export * from "./quote.svg";
export * from "./substack.svg";
export * from "./twitter.svg";
export * from "./x.svg";
