import { IconTypes } from "./icon-types";
import {
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowTriangleLeft,
  CheckBox,
  Close,
  Dev,
  Email,
  Github,
  LinkedIn,
  Mastodon,
  Medium,
  OpenInNew,
  ProductHunt,
  Quote,
  Substack,
  Telegram,
  Twitter,
  Website,
  X,
} from "./svg";

export const ICON_TYPE_SVGS = {
  [IconTypes.ArrowChevronLeft]: ArrowChevronLeft,
  [IconTypes.ArrowChevronRight]: ArrowChevronRight,
  [IconTypes.ArrowTriangleLeft]: ArrowTriangleLeft,
  [IconTypes.ArrowTriangleRight]: ArrowTriangleLeft,
  [IconTypes.Close]: Close,
  [IconTypes.CheckBox]: CheckBox,
  [IconTypes.Dev]: Dev,
  [IconTypes.Email]: Email,
  [IconTypes.Github]: Github,
  [IconTypes.LinkedIn]: LinkedIn,
  [IconTypes.Mastodon]: Mastodon,
  [IconTypes.Medium]: Medium,
  [IconTypes.ProductHunt]: ProductHunt,
  [IconTypes.OpenInNew]: OpenInNew,
  [IconTypes.Quote]: Quote,
  [IconTypes.Substack]: Substack,
  [IconTypes.Telegram]: Telegram,
  [IconTypes.Twitter]: Twitter,
  [IconTypes.Website]: Website,
  [IconTypes.X]: X,
};
