import { Inter } from "next/font/google";

import "./globals.css";
import { Header } from "./components";
import { Container } from "@mui/material";
import { useSelectedTheme } from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Container maxWidth="md">
          <Header />

          {children}
        </Container>
      </body>
    </html>
  );
}
